const mongoose = require("mongoose");

// the name after the slash is the name of the database, for our example it is test-app
// mongodb+srv://${process.env.MONGODB_USERNAME}:${process.env.MONGODB_PASSWORD}.rnw2g.mongodb.net/test-app
mongoose.connect(
    `mongodb+srv://test-user:n3VTiTTCqWFPn74y@cluster0.rnw2g.mongodb.net/test-app`
);

// mongoose's model method can take 3 arguments
// 1. the name of the model
// 2. the schema of the model
// 3. the name of the collection in the database (optional)
// if the 3rd argument is not provided, mongoose will use the pluralized version of the model name
const User = mongoose.model("Cat", { name: String });

// the model method returns a constructor function
// the constructor function can be used to create new documents
const kitty = new User({ name: "Rouch" });

// the constructor function has a save method that can be used to save the document to the database
// the save method returns a promise
// res._id.toString()) is used to convert the id to a string, the _id is an object, auto generated by mongodb
kitty.save().then((res) => console.log(res._id.toString()));
